version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.2
  - dependency-name: uglify-js
    versions:
    - 3.12.3
    - 3.12.6
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: tslib
    versions:
    - 2.0.3
